# Staging Environment Configuration
# Scaled configuration for staging environment testing

# AWS Configuration - Staging Scale
aws:
  organization:
    management_account_id: "222222222222"
    organization_units:
      - name: "Staging"
        accounts: 50
      - name: "Development" 
        accounts: 30
      - name: "Testing"
        accounts: 20
        
  regions:
    primary: "us-east-1"
    secondary: "us-west-2"
    
  accounts_per_batch: 10
  max_concurrent_deployments: 20
  deployment_timeout: 3600  # 1 hour
  
  cross_account_role: "arn:aws:iam::*:role/OrganizationAccountAccessRole"
  
# GCP Configuration - Staging Scale
gcp:
  organization_id: "987654321098"
  folders:
    - name: "Staging"
      projects: 50
    - name: "Development"
      projects: 30  
    - name: "Testing"
      projects: 20
      
  regions:
    primary: "us-central1"
    secondary: "us-west1"
    
  projects_per_batch: 8
  max_concurrent_deployments: 15

# Azure Configuration - Staging Scale
azure:
  tenant_id: "87654321-4321-4321-4321-210987654321"
  management_groups:
    - name: "Staging"
      subscriptions: 50
    - name: "Development"
      subscriptions: 30
    - name: "Testing"
      subscriptions: 20
      
  regions:
    primary: "East US"
    secondary: "West US 2"
    
  subscriptions_per_batch: 5
  max_concurrent_deployments: 12

# Staging Security Configuration
security:
  zero_trust:
    enabled: true
    default_deny: true
    continuous_verification: true
    
  multi_factor_authentication:
    required: true
    hardware_keys_preferred: false
    backup_methods: 2
    
  privileged_access_management:
    just_in_time_access: true
    approval_workflow: true
    session_recording: true
    max_session_duration: 3600  # 1 hour
    
  encryption:
    customer_managed_keys: true
    key_rotation_days: 180
    hsm_backed: false
    
  network_security:
    vpc_isolation: true
    private_endpoints: true
    network_segmentation: true
    
  audit_logging:
    comprehensive: true
    tamper_proof: true
    real_time_analysis: true
    retention_years: 3

# Staging Compliance
compliance:
  frameworks:
    - name: "SOC2_TYPE2"
      evidence_collection: true
      continuous_monitoring: true
    - name: "ISO27001"
      risk_assessments: true
      incident_response: true
      
  data_governance:
    data_classification: true
    data_lineage: true
    data_retention: true
    
  privacy:
    gdpr_compliance: true
    data_minimization: true
    consent_management: true

# Staging Monitoring
monitoring:
  sla:
    availability: 99.9
    response_time_p95: 3000  # milliseconds
    error_rate_max: 0.5      # percentage
    
  observability:
    distributed_tracing: true
    synthetic_monitoring: true
    real_user_monitoring: false
    
  alerting:
    escalation_policies: true
    alert_fatigue_prevention: true
    intelligent_routing: false
    
  dashboards:
    executive_summary: false
    operational_dashboards: true
    business_metrics: false
    
  capacity_planning:
    predictive_scaling: false
    resource_forecasting: true
    cost_optimization: true

# Staging Disaster Recovery
disaster_recovery:
  recovery_time_objective: 60  # minutes
  recovery_point_objective: 15  # minutes
  
  backup_strategy:
    frequency: "hourly"
    cross_region: true
    cross_cloud: false
    encryption: true
    testing_schedule: "weekly"
    
  failover:
    automated: false
    health_checks: true
    traffic_routing: true
    
  business_continuity:
    communication_plan: true
    stakeholder_notifications: true
    status_page_updates: true

# Staging Performance
performance:
  scalability:
    horizontal_scaling: true
    auto_scaling: true
    load_balancing: true
    
  caching:
    multi_layer: true
    distributed: false
    intelligent_invalidation: true
    
  database:
    read_replicas: true
    connection_pooling: true
    query_optimization: true
    
  cdn:
    global_distribution: false
    edge_caching: true
    origin_shielding: false

# Staging Cost Management
cost_management:
  budgets:
    total_monthly: 25000  # USD
    per_cloud_limit: 10000  # USD
    alert_thresholds: [70, 85, 95, 100]
    
  optimization:
    reserved_instances: false
    spot_instances: true
    rightsizing: true
    unused_resource_cleanup: true
    
  reporting:
    daily_reports: false
    cost_attribution: true
    forecasting: true
    anomaly_detection: true

# Staging Operations
operations:
  deployment:
    blue_green: true
    canary_releases: true
    feature_flags: true
    automated_rollback: true
    
  change_management:
    approval_workflows: true
    change_windows: false
    rollback_procedures: true
    communication_plans: true
    
  incident_management:
    automated_detection: true
    escalation_procedures: true
    post_incident_reviews: true
    knowledge_base: true
    
  capacity_management:
    resource_planning: true
    performance_baselines: true
    growth_forecasting: true

# Staging Integration
integrations:
  service_mesh: "istio"
  secrets_management: "vault"
  certificate_management: "cert-manager" 
  policy_engine: "open-policy-agent"
  
  ci_cd:
    multi_stage_pipelines: true
    security_scanning: true
    compliance_checks: true
    automated_testing: true
    
  itsm:
    ticket_integration: false
    change_tracking: true
    asset_management: true
