name: 'Setup Cloud CLIs'
description: 'Setup AWS CLI, Azure CLI, and gcloud CLI'

inputs:
  terraform_version:
    description: 'Terraform version to install'
    required: false
    default: '1.5.7'
  aws_cli_version:
    description: 'AWS CLI version to install'
    required: false
    default: '2'
  python_version:
    description: 'Python version for additional tools'
    required: false
    default: '3.11'

runs:
  using: 'composite'
  steps:
    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}
    
    - name: 'Setup Python'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
    
    - name: 'Install AWS CLI v2'
      shell: bash
      run: |
        if ! command -v aws &> /dev/null; then
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
        fi
        aws --version
    
    - name: 'Install Azure CLI'
      shell: bash
      run: |
        if ! command -v az &> /dev/null; then
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        fi
        az --version
    
    - name: 'Install Google Cloud CLI'
      shell: bash
      run: |
        if ! command -v gcloud &> /dev/null; then
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update && sudo apt-get install google-cloud-cli
        fi
        gcloud --version
    
    - name: 'Install Additional Tools'
      shell: bash
      run: |
        # Install jq for JSON processing
        sudo apt-get install -y jq
        
        # Install terraform security tools
        pip install checkov tfsec
        
        # Install cloud-specific tools
        pip install boto3 google-cloud-iam azure-identity azure-mgmt-authorization
